trigger:
  branches:
    include:
      - feature/*
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  TF_WORKING_DIR: 'environments/dev'

steps:
  - script: |
      curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
      sudo apt-add-repository "deb https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      sudo apt-get update
      sudo apt-get install -y terraform
      terraform version
    displayName: 'Install Terraform'

  - script: |
      terraform fmt -check -recursive
    displayName: 'Terraform Format Check'

  - task: AzureCLI@2
    displayName: 'Terraform Init'
    inputs:
      azureSubscription: 'azure-sp-terraform'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      workingDirectory: '$(TF_WORKING_DIR)'
      inlineScript: |
        terraform init

  - task: AzureCLI@2
    displayName: 'Terraform Validate'
    inputs:
      azureSubscription: 'azure-sp-terraform'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      workingDirectory: '$(TF_WORKING_DIR)'
      inlineScript: |
        terraform validate

  - task: AzureCLI@2
    displayName: 'Terraform Plan'
    inputs:
      azureSubscription: 'azure-sp-terraform'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      workingDirectory: '$(TF_WORKING_DIR)'
      inlineScript: |
        terraform plan \
          -var="ssh_public_key=$(SSH_PUBLIC_KEY)" \
          -out=tfplan